@startuml classe_de_análise

class Pessoa {
    Nome: String
    CPF: String
    Data_De_Nascimento: Date
    Profissão: String
    incluirPessoa(): Int
    alterarPessoa(): Int
    consultarPessoa(): String
    excluirPessoa(): Int
}

@enduml



