@startuml club_social

class Socio {
    numero_cartao: Integer
    nome: String
    endereco: String
    telefone: String
    cpf: String
    rg: String
    data_nascimento: Date
    validarCpf(): Integer
    incluirSocio(): Integer
    consultarSocio(): String
    atualizarSocio(): Integer
    deletarSocio(): Integer
}

class Dependente {
    numero_cartao: Integer
    nome: String
    parentesco: String
    email: String
    validarEmail(): Integer
    validarNumero(): Integer
    registrarDependente(): Integer
    atualizarDependente(): Integer
    consultarDependente(): String
    deletarDependente(): Integer
}

class Categoria {
    incluirCategoria(): Integer
    atualizarCategoria(): Integer
    consultarCategoria(): String
    deletarCategoria(): Integer
}

class Mensalidade {
    data_pagamento: Date
    valor: Decimal
    data_efetivamente_paga: Date
    possiveis_juros: Decimal
    valor_efetivamente_pago: Decimal
    esta_quitado: Boolean
    consultarMensalidade(): String
    calcualarJuros(): Decimal
    quitarMensalidade(): Integer
}

Socio "1" -- "1..*" Dependente  : tem >
Socio "1" -- "1"    Categoria   : pertence >
Socio "1" -- "0..*" Mensalidade : paga >

@enduml